name: amd64 Windows

on:
  push:
  pull_request:

jobs:
  # Building using the github runner environement directly.
  bazel:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python --version
    - name: Install Bazel
      run: choco install bazel
    - name: Check Bazel
      run: bazel version
    - name: Build
      run: bazel build -s --cxxopt="-std:c++17" //...:all
    - name: Test
      run: bazel test --test_output=errors --cxxopt="-std:c++17" //...:all
